package com.exam;
// Generated Jun 5, 2016 3:32:02 PM by Hibernate Tools 4.3.1


import java.sql.Date;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int id;
     private String name;
     @NotEmpty
     @Pattern(regexp = "[a-zA-Z0-9_]+[@][a-z]+[.][a-z]{2,3}$", message =  "invalid email")
     private String email;
     private String password;
     private Date dob;

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String name, String email, String password, Date dob) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
       this.dob = dob;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }




}


